# Site settings
destination: ../../public/blog
title: HoffsMH
description: >
  Small blog for me, the junior developer

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://mhecker/blog" # the base hostname & protocol for your site
paginate_path: "blog/page:num"
permalink: blog/:title/

author:
  fullname: Matthew Hecker
  github: HoffsMH
  # twitter:
  # disqus: your_disqus_username

google_analytics: 'UA-69553422-1'

gems: [jekyll-paginate]
# Build settings
markdown: redcarpet
paginate: 5
exclude: ['vendor']
